[versions]
shadow = "9.6.1"
paper-api = "1.21.4-R0.1-SNAPSHOT"
jgit = "7.7.1.202607240634-r"
json = "20250517"
junit = "5.10.2"
junit-platform = "1.10.2"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
eclipse-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
json = { module = "org.json:json", version.ref = "json" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }